# .goreleaser.yml
# Build customization

project_name: gocd-tf-generate

builds:
  - binary: gocd-tf-generate
    env:
      - CGO_ENABLED=0
    ldflags: -w -s -X main.Version={{ .Version }}
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7

archive:
  name_template: "gocd-tf-generate-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    386: i386
    amd64: x86_64

  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md

fpm:
  homepage: https://github.com/drewsonne/gocd-tf-generate
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  license: LGPLv3
  formats:
#    - deb
    - rpm
  dependencies:
    - git

brew:
  github:
    owner: drewsonne
    name: homebrew-devops
  homepage: https://github.com/drewsonne/gocd-tf-generate
  test: |
    system "#{bin}/gocd-tf-generate"
